from __future__ import annotations

import argparse
import json
import re
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path
from xml.etree import ElementTree as ET

from pypdf import PdfReader


TEXT_EXTENSIONS = {".txt", ".md"}
IMAGE_EXTENSIONS = {".png", ".jpg", ".jpeg", ".webp", ".bmp", ".tif", ".tiff"}
AUDIO_VIDEO_EXTENSIONS = {".mp3", ".wav", ".m4a", ".aac", ".flac", ".mp4", ".mov", ".mkv"}


@dataclass
class MaterialRecord:
    source_file: str
    source_type: str
    status: str
    output_file: str | None = None
    notes: str = ""
    chars_extracted: int = 0


def _clean_text(text: str) -> str:
    text = text.replace("\x00", "")
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def _write_processed(processed_dir: Path, source: Path, source_type: str, body: str) -> Path:
    processed_dir.mkdir(parents=True, exist_ok=True)
    target = processed_dir / f"{source.stem}.txt"
    header = (
        f"# Source: {source.name}\n"
        f"# Source type: {source_type}\n"
        "# Generated by scripts/ingest_materials.py\n\n"
    )
    target.write_text(header + _clean_text(body) + "\n", encoding="utf-8")
    return target


def extract_pdf(path: Path) -> tuple[str, str]:
    reader = PdfReader(str(path))
    pages: list[str] = []
    for page_number, page in enumerate(reader.pages, 1):
        text = page.extract_text() or ""
        pages.append(f"\n\n--- Page {page_number} ---\n{text}")
    body = _clean_text("".join(pages))
    avg_chars = len(body) / max(1, len(reader.pages))
    note = f"{len(reader.pages)} pages extracted."
    if avg_chars < 80:
        note += " Low text density detected; OCR is likely needed."
    return body, note


def extract_text_file(path: Path) -> tuple[str, str]:
    return path.read_text(encoding="utf-8", errors="ignore"), "Plain text copied."


def _zip_xml_text(path: Path, members: list[str]) -> str:
    texts: list[str] = []
    with zipfile.ZipFile(path) as archive:
        for member in members:
            try:
                root = ET.fromstring(archive.read(member))
            except Exception:
                continue
            for node in root.iter():
                if node.tag.endswith("}t") and node.text:
                    texts.append(node.text)
            texts.append("\n")
    return "\n".join(texts)


def extract_docx(path: Path) -> tuple[str, str]:
    body = _zip_xml_text(path, ["word/document.xml"])
    return body, "DOCX text extracted from word/document.xml."


def extract_pptx(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        slide_members = sorted(
            name
            for name in archive.namelist()
            if name.startswith("ppt/slides/slide") and name.endswith(".xml")
        )
    body = _zip_xml_text(path, slide_members)
    return body, f"PPTX text extracted from {len(slide_members)} slide XML files."


def ingest_materials(raw_dir: Path, processed_dir: Path, outputs_dir: Path) -> list[MaterialRecord]:
    records: list[MaterialRecord] = []
    outputs_dir.mkdir(parents=True, exist_ok=True)
    for path in sorted(p for p in raw_dir.iterdir() if p.is_file()):
        ext = path.suffix.lower()
        try:
            if ext == ".pdf":
                body, note = extract_pdf(path)
                target = _write_processed(processed_dir, path, "pdf", body)
                status = "needs_ocr" if "OCR is likely needed" in note else "processed"
                records.append(MaterialRecord(path.name, "pdf", status, target.name, note, len(body)))
            elif ext in TEXT_EXTENSIONS:
                body, note = extract_text_file(path)
                target = _write_processed(processed_dir, path, ext.lstrip("."), body)
                records.append(MaterialRecord(path.name, ext.lstrip("."), "processed", target.name, note, len(body)))
            elif ext == ".docx":
                body, note = extract_docx(path)
                target = _write_processed(processed_dir, path, "docx", body)
                status = "needs_review" if len(body.strip()) < 200 else "processed"
                records.append(MaterialRecord(path.name, "docx", status, target.name, note, len(body)))
            elif ext == ".pptx":
                body, note = extract_pptx(path)
                target = _write_processed(processed_dir, path, "pptx", body)
                status = "needs_review" if len(body.strip()) < 200 else "processed"
                records.append(MaterialRecord(path.name, "pptx", status, target.name, note, len(body)))
            elif ext in IMAGE_EXTENSIONS:
                records.append(
                    MaterialRecord(
                        path.name,
                        "image",
                        "needs_ocr",
                        None,
                        "Image-based material detected. Route to Google Docs OCR, Gemini Vision OCR, or another OCR tool.",
                    )
                )
            elif ext in AUDIO_VIDEO_EXTENSIONS:
                records.append(
                    MaterialRecord(
                        path.name,
                        "audio_video",
                        "needs_transcription",
                        None,
                        "Audio/video material detected. Route to Whisper or another transcription tool before exam generation.",
                    )
                )
            elif path.name.lower() == "desktop.ini":
                records.append(MaterialRecord(path.name, "system_file", "ignored", None, "Windows folder metadata ignored."))
            else:
                records.append(MaterialRecord(path.name, ext.lstrip(".") or "unknown", "unsupported", None, "No extractor configured."))
        except Exception as exc:
            records.append(MaterialRecord(path.name, ext.lstrip(".") or "unknown", "failed", None, str(exc)))

    manifest_path = outputs_dir / "materials_manifest.json"
    manifest_path.write_text(json.dumps([asdict(r) for r in records], indent=2, ensure_ascii=False), encoding="utf-8")
    report_path = outputs_dir / "unsupported_materials_report.md"
    report_path.write_text(render_report(records), encoding="utf-8")
    return records


def render_report(records: list[MaterialRecord]) -> str:
    lines = [
        "# Materials Ingestion Report",
        "",
        "| Source | Type | Status | Output | Notes |",
        "| --- | --- | --- | --- | --- |",
    ]
    for record in records:
        output = record.output_file or "-"
        note = record.notes.replace("\n", " ")
        lines.append(f"| {record.source_file} | {record.source_type} | {record.status} | {output} | {note} |")

    flagged = [r for r in records if r.status in {"needs_ocr", "needs_transcription", "unsupported", "failed", "needs_review"}]
    lines += ["", "## Human Follow-Up", ""]
    if not flagged:
        lines.append("- No follow-up needed.")
    else:
        for record in flagged:
            lines.append(f"- `{record.source_file}`: {record.status}. {record.notes}")
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description="Ingest lecture materials into processed text files.")
    parser.add_argument("--raw-dir", default="lecture_notes/raw")
    parser.add_argument("--processed-dir", default="lecture_notes/processed")
    parser.add_argument("--outputs-dir", default="outputs")
    args = parser.parse_args()

    root = Path(__file__).resolve().parents[1]
    records = ingest_materials(root / args.raw_dir, root / args.processed_dir, root / args.outputs_dir)
    processed = sum(1 for r in records if r.status == "processed")
    flagged = sum(1 for r in records if r.status != "processed" and r.status != "ignored")
    print(f"Ingested {processed} material(s); {flagged} need follow-up.")
    print(f"Wrote report to {root / args.outputs_dir / 'unsupported_materials_report.md'}")


if __name__ == "__main__":
    main()
